main:
    params: [input]
    steps:
    - start:
        call: sys.log
        args:
            text: ${input}
    - vars:
        assign:
            - report_id: ${input.reportId}
            - bucket_input: "gs://smart-expenses-incoming-receipts/"
            - bucket_output: "gs://smart-expenses-parsed-receipts/"
            - project: ${sys.get_env("GOOGLE_CLOUD_PROJECT_ID")}
    - update_status_to_submitted:
        call: update_firestore
        args:
            report_id: ${report_id}
            field: "status"
            value: "PROCESSING"
            
    - invoke_document_ai:
        call: googleapis.documentai.v1.projects.locations.processors.batchProcess
        args:
            name: ${"projects/" + project + "/locations/eu/processors/c799b15b13e7c838"}
            location: "eu"
            body:
                inputDocuments:
                    gcsPrefix:
                        gcsUriPrefix: ${bucket_input + report_id}
                documentOutputConfig:
                    gcsOutputConfig: 
                        gcsUri: ${bucket_output + report_id}
                skipHumanReview: true
        result: document_ai_response
    - log_document_ai_response:
        call: sys.log
        args:
            text: ${document_ai_response}

    - check_error_or_response:
        switch:
            - condition: ${"error" in document_ai_response}
              next: on_error
        next: process_annotations
    - on_error:
        call: update_firestore
        args:
            report_id: ${report_id}
            field: "status"
            value: "ERROR"
    - return_error:
        return: ${document_ai_response.error}
    
    - process_annotations:
        call: http.post
        args:
            url: https://europe-west1-easy-ai-serverless.cloudfunctions.net/process-annotations
            auth:
                type: OIDC
            body:
                report_id: ${report_id}
                bucket_path: ${bucket_output}
        result: process_annotations_result
    - log_process_annotations_result:
        call: sys.log
        args:
            text: ${process_annotations_result}

    - create_callback:
        call: events.create_callback_endpoint
        args:
            http_callback_method: "POST"
        result: callback_details
    - log_callback_details:
        call: sys.log
        args:
            text: ${callback_details}

    - store_callback_details:
        call: update_firestore
        args:
            report_id: ${report_id}
            field: "callback"
            value: ${callback_details.url}
    - update_status_to_awaiting_approval:
        call: update_firestore
        args:
            report_id: ${report_id}
            field: "status"
            value: "AWAITING"
    - await_callback:
        try:
            call: events.await_callback
            args:
                callback: ${callback_details}
                timeout: 3600
            result: callback_request
        except:
            as: e
            steps:
                - update_status_to_error:
                    call: update_firestore
                    args:
                        report_id: ${report_id}
                        field: "status"
                        value: "ERROR"
                - log_error:
                    call: sys.log
                    args:
                        severity: "ERROR"
                        text: ${"Awaiting callback error " + e.message}
                    next: return_final_step
    - assign_approval:
        assign:
            - approved: ${callback_request.http_request.body.approved}
    
    - store_approval:
        switch:
            - condition: ${callback_request.http_request.body.approved}
              steps:
                    - store_approved:
                        call: update_firestore
                        args:
                            report_id: ${report_id}
                            field: "status"
                            value: "APPROVED"
            - condition: ${not callback_request.http_request.body.approved}
              steps:
                    - store_rejected:
                        call: update_firestore
                        args:
                            report_id: ${report_id}
                            field: "status"
                            value: "REJECTED"
    - return_final_step:
        return: ${document_ai_response.metadata}

update_firestore:
    params: [report_id, field, value, type: "string"]
    steps:
        - define_db_root:
            assign:
                - database_root: ${"projects/" + sys.get_env("GOOGLE_CLOUD_PROJECT_ID") + "/databases/(default)/documents/requests/"}
                - firestoreType: ${type + "Value"}
                - fieldTypeAndValue: {}
                - fieldTypeAndValue[firestoreType]: ${value}
                - body: {fields: {}}
                - body.fields[field]: ${fieldTypeAndValue}
        - log_firestore_change_request:
            call: sys.log
            args:
                text: ${report_id + " > " + field + " = " + json.encode_to_string(value) + " (" + type + ")"}
        - patch_doc_firestore:
            call: googleapis.firestore.v1.projects.databases.documents.patch
            args:
                name: ${database_root + report_id}
                updateMask:
                    fieldPaths: [${field}]
                body: ${body}
            result: firestore_update_result
        - log_firestore_change_response:
            call: sys.log
            args:
                text: ${firestore_update_result}